/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Engagement {
      
    export type EngagementRecordStruct = {creator: AddressLike, husbandName: string, wifeName: string, husbandCccdHash: BytesLike, wifeCccdHash: BytesLike, husbandPromise: string, wifePromise: string, timestamp: BigNumberish}

    export type EngagementRecordStructOutput = [creator: string, husbandName: string, wifeName: string, husbandCccdHash: string, wifeCccdHash: string, husbandPromise: string, wifePromise: string, timestamp: bigint] & {creator: string, husbandName: string, wifeName: string, husbandCccdHash: string, wifeCccdHash: string, husbandPromise: string, wifePromise: string, timestamp: bigint }
  
    }

  export interface EngagementInterface extends Interface {
    getFunction(nameOrSignature: "createEngagement" | "engagementCount" | "getAllEngagements" | "getEngagement" | "owner" | "setSystemFeeWei" | "systemFeeWei" | "transferOwnership" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EngagementCreated" | "OwnershipTransferred" | "SystemFeeUpdated" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'createEngagement', values: [string, string, BytesLike, BytesLike, string, string]): string;
    encodeFunctionData(functionFragment: 'engagementCount', values?: undefined): string;
    encodeFunctionData(functionFragment: 'getAllEngagements', values?: undefined): string;
    encodeFunctionData(functionFragment: 'getEngagement', values: [BigNumberish]): string;
    encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
    encodeFunctionData(functionFragment: 'setSystemFeeWei', values: [BigNumberish]): string;
    encodeFunctionData(functionFragment: 'systemFeeWei', values?: undefined): string;
    encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
    encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createEngagement', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'engagementCount', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'getAllEngagements', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'getEngagement', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'setSystemFeeWei', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'systemFeeWei', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace EngagementCreatedEvent {
      export type InputTuple = [engagementId: BigNumberish, creator: AddressLike, husbandName: string, wifeName: string, timestamp: BigNumberish];
      export type OutputTuple = [engagementId: bigint, creator: string, husbandName: string, wifeName: string, timestamp: bigint];
      export interface OutputObject {engagementId: bigint, creator: string, husbandName: string, wifeName: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SystemFeeUpdatedEvent {
      export type InputTuple = [oldFeeWei: BigNumberish, newFeeWei: BigNumberish];
      export type OutputTuple = [oldFeeWei: bigint, newFeeWei: bigint];
      export interface OutputObject {oldFeeWei: bigint, newFeeWei: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, amount: bigint];
      export interface OutputObject {owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Engagement extends BaseContract {
    
    connect(runner?: ContractRunner | null): Engagement;
    waitForDeployment(): Promise<this>;

    interface: EngagementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createEngagement: TypedContractMethod<
      [husbandName: string, wifeName: string, husbandCccdHash: BytesLike, wifeCccdHash: BytesLike, husbandPromise: string, wifePromise: string, ],
      [bigint],
      'payable'
    >
    

    
    engagementCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAllEngagements: TypedContractMethod<
      [],
      [Engagement.EngagementRecordStructOutput[]],
      'view'
    >
    

    
    getEngagement: TypedContractMethod<
      [engagementId: BigNumberish, ],
      [Engagement.EngagementRecordStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setSystemFeeWei: TypedContractMethod<
      [newFeeWei: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    systemFeeWei: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createEngagement'): TypedContractMethod<
      [husbandName: string, wifeName: string, husbandCccdHash: BytesLike, wifeCccdHash: BytesLike, husbandPromise: string, wifePromise: string, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'engagementCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAllEngagements'): TypedContractMethod<
      [],
      [Engagement.EngagementRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getEngagement'): TypedContractMethod<
      [engagementId: BigNumberish, ],
      [Engagement.EngagementRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setSystemFeeWei'): TypedContractMethod<
      [newFeeWei: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'systemFeeWei'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EngagementCreated'): TypedContractEvent<EngagementCreatedEvent.InputTuple, EngagementCreatedEvent.OutputTuple, EngagementCreatedEvent.OutputObject>;
    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    getEvent(key: 'SystemFeeUpdated'): TypedContractEvent<SystemFeeUpdatedEvent.InputTuple, SystemFeeUpdatedEvent.OutputTuple, SystemFeeUpdatedEvent.OutputObject>;
    getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'EngagementCreated(uint256,address,string,string,uint256)': TypedContractEvent<EngagementCreatedEvent.InputTuple, EngagementCreatedEvent.OutputTuple, EngagementCreatedEvent.OutputObject>;
      EngagementCreated: TypedContractEvent<EngagementCreatedEvent.InputTuple, EngagementCreatedEvent.OutputTuple, EngagementCreatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'SystemFeeUpdated(uint256,uint256)': TypedContractEvent<SystemFeeUpdatedEvent.InputTuple, SystemFeeUpdatedEvent.OutputTuple, SystemFeeUpdatedEvent.OutputObject>;
      SystemFeeUpdated: TypedContractEvent<SystemFeeUpdatedEvent.InputTuple, SystemFeeUpdatedEvent.OutputTuple, SystemFeeUpdatedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }